<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-01-26 14:28

$extensionPath = t3lib_extMgm::extPath('causal_accounts');
return array(
	'tx_causalaccounts_synchronizationtask' => $extensionPath . 'class.tx_causalaccounts_synchronizationtask.php',
);
?>